# Generated by Django 4.1.7 on 2023-05-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("emp_id", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("age", models.IntegerField()),
                ("address", models.TextField()),
                ("full_time", models.BooleanField()),
                ("designation", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
