# Generated by Django 4.1.7 on 2023-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_employee_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="picture",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
