# Generated by Django 5.0.4 on 2024-04-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_employee_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="id",
        ),
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_time",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="picture",
            field=models.ImageField(default="default.jpg", upload_to=""),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.PositiveIntegerField(),
        ),
    ]
