# Generated by Django 2.2.14 on 2023-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_booksmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
